### ISSUE TITLE
html sections

### ISSUE THREAD

**Issue by rimmesbe** [Caradt05/prj-rev-bwfs-dasmoto#1]
Good job using divs to create sections in the html. I would move the id's from the h2's into the divs instead so that you can target each section individually. Also, make sure you are using correct indentation.
<img width="122" alt="screen shot 2017-06-28 at 1 57 34 pm" src="https://user-images.githubusercontent.com/9957628/36622389-ea020ac8-18ca-11e8-9c66-0c584ddba408.png">

https://github.com/Caradt05/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/index.html#L9-L14

**Comment by Caradt05** [comment]
What would the correct indentation here be?

**Comment by rimmesbe** [comment]
Child elements need to be indented further than the parent element:
<img width="201" alt="screen shot 2017-11-01 at 1 26 49 pm" src="https://user-images.githubusercontent.com/9957628/36633122-c2258140-195d-11e8-8e38-50e92cfd77f4.png">
