### ISSUE TITLE
good use of class

### ISSUE THREAD

**Issue by rimmesbe** [Caradt05/prj-rev-bwfs-dasmoto#5]
This is a good use of class and a good name as it describes the component being styled. If you want you could swap out the `<span>` tag for a `<strong>` tag which defaults to bold.

https://github.com/Caradt05/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's/resources/style.css#L19-L20

**Comment by Caradt05** [comment]
my thinking here was that if I used a < strong > tag all (hypothetical) future < strong > elements would be affected, so why not be more specific? I originally used < strong > but changed it.
